In [17]:
import torch
assert torch.cuda.is_available()
device = torch.device("cuda:0")
import h5py
import numpy as np

In [18]:
data_dir = '../data/'
train_dist = 'training/l2_dist/'

In [19]:
a = torch.randn(2, 4)
a.to(device)
b = a.detach().cpu().clone().numpy()
print(type(b))

<class 'numpy.ndarray'>


In [22]:
def load_dist(fname):
    file = h5py.File(fname, 'r')
    dkey = list(file.keys())[0]
    dset = file[dkey]
    nData = np.array(dset)
    nData = np.transpose(nData)

    vertice = nData[:]
    nd_vert = np.array(vertice)
    nd_vert = nd_vert.astype(float)
    t_vert = torch.from_numpy(nd_vert)

    return t_vert

In [24]:
fn = ''.join([data_dir, train_dist, 'tr_reg_dist_', '000', '.h5'])
a = load_dist(fn)
print(a.shape)

torch.Size([6890, 6890])


In [9]:
a = torch.unsqueeze(torch.tensor([[1, 2, 3], [2, 3, 4], [3, 4, 5]]), 0).to(device)
# print(2 in a)
# for i in range(3)
#     c = torch.where(torch.eq(a[0], i))
b = 1
c = 0
c += b
c += b
print(c)

2


In [23]:
a = torch.tensor([[1, 2, 3], [1, 2, 3]])
b = torch.tensor([[4, 5, 6], [4, 5, 6]])
c = b @ a.transpose(1, 0)
d = torch.matmul(b, a.transpose(1, 0))
e = a.transpose(1, 0) @ b
f = a.transpose(1, 0) @ b
f = f.unsqueeze(0)
print(c)
print(d)
print(e)
print(f)
print(f.size())
g = torch.empty(f.size(0), f.size(1), f.size(2)).unsqueeze(0)
g = torch.empty(f.size(0)).unsqueeze(0)
print(g.size())
g = f.unsqueeze(0)
# h = torch.cat((g, f.unsqueeze(0)), dim=0)
h = torch.cat((g, f.unsqueeze(0)), dim=0)
i = f.unsqueeze(0)
i = torch.cat((i, f.unsqueeze(0)), dim=0)

print(h)
print(i)

tensor([[32, 32],
        [32, 32]])
tensor([[32, 32],
        [32, 32]])
tensor([[ 8, 10, 12],
        [16, 20, 24],
        [24, 30, 36]])
tensor([[[ 8, 10, 12],
         [16, 20, 24],
         [24, 30, 36]]])
torch.Size([1, 3, 3])
torch.Size([1, 1])
tensor([[[[ 8, 10, 12],
          [16, 20, 24],
          [24, 30, 36]]],


        [[[ 8, 10, 12],
          [16, 20, 24],
          [24, 30, 36]]]])
tensor([[[[ 8, 10, 12],
          [16, 20, 24],
          [24, 30, 36]]],


        [[[ 8, 10, 12],
          [16, 20, 24],
          [24, 30, 36]]]])


In [11]:
a = torch.randn(2, 3)
if True:
    C = a.unsqueeze(0)[:,  :2, :]
print(C)
print(C.size(1))

tensor([[[-0.4818, -0.0703,  0.8571],
         [ 0.2054, -1.2502, -1.0211]]])
2


In [2]:
cuda_device = torch.device("cuda") if torch.cuda.is_available() else torch.device('cpu')

In [18]:
with torch.cuda.device(0):
    a = torch.randn(3, 3).to(device=cuda_device)
    print(a)
    res = torch.norm(a)
    print(res)
    
    b = a.flatten()
    print(b)
    res2 = torch.norm(b)
    print(res2)
    
#     c = torch.randn(5, 5).to(device=cuda_device)
    res3 = torch.norm(a[0])
    res4 = torch.norm(a[1])
    res5 = torch.norm(a[2])
    print(res3)
    print(res4)
    print(res5)

tensor([[ 1.3770, -0.0073, -0.1430],
        [-2.1186, -1.9270,  2.0436],
        [-0.5770,  0.9278, -0.0263]], device='cuda:0')
tensor(3.9356, device='cuda:0')
tensor([ 1.3770, -0.0073, -0.1430, -2.1186, -1.9270,  2.0436, -0.5770,  0.9278,
        -0.0263], device='cuda:0')
tensor(3.9356, device='cuda:0')
tensor(1.3844, device='cuda:0')
tensor(3.5182, device='cuda:0')
tensor(1.0929, device='cuda:0')


In [ ]:
# memory load
# def get_shot_dic(parr):
#     # create shot dictionary in inter - intra pair order
#     # if only one of them is loaded, then only that intra or inter challenge is loaded
#     shot_dic = {}
#     print("Start generating dictionary, it will take a while")
# #     print(parr)
#     for i in range(100):
# #         print(parr[i])
#         fn1 = ''.join([data_dir, test_shot, 'test_scan_d_res_', parr[i][0], '.txt'])
#         fn2 = ''.join([data_dir, test_shot, 'test_scan_d_res_', parr[i][1], '.txt'])
#         shot1 = load_shot(fn1)
#         shot2 = load_shot(fn2)
#         shot_dic[tuple(parr[i])] = [shot1, shot2]
#     print("Finished generating shot dictionary!")   
#     return shot_dic

In [1]:
a = [x for x in range(1000)]
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,

In [ ]:
# def corr_vert_dist(des, des2):
#     sum_l2_norm = []
#     print(torch.sub(des[0], des2[0]).size())
#     for i in range(len(des)):
#         sum_l2_norm.append(torch.norm(torch.sub(des[i], des2[i])[:]))
#     print(len(sum_l2_norm))
#     return sum_l2_norm

In [ ]:
def compute_l2(des, des2):
    l2_dist = []
    with torch.cuda.device(0):
#         dist = torch.matmul(des, torch.transform(des2))
        for i in range(0,des.shape[0]):
            row = []
            for j in range(0,des2.shape[0]):
                l2_norm = torch.norm(des[i]-des2[j])
#                 l2_norm = torch.sqrt(torch.sum(torch.square(des[i][0:]-des2[j][0:])))
                row.append(l2_norm)
#             np_row = np.array(row)
    #         print(np_row.shape)
            l2_dist.append(row)
        print(len(l2_dist))
#         np_dist = np.array(l2_dist)
        dist = torch.as_tensor(l2_dist)
        print(dist.shape)
    gc.collect()
    torch.cuda.empty_cache()
    return dist

In [8]:
a = torch.tensor([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [0., 1., 2.]])
b = torch.tensor([[3., 2., 1.], [6., 5., 4.], [9., 8., 7.], [2., 1., 0.]])
d = torch.cat([torch.unsqueeze(a[0], dim=0), torch.unsqueeze(b[0], dim=0)], dim=0)
print(d.size())
c = torch.cdist(a, b, p=2)
print(c)
print(l2_norm)

torch.Size([2, 3])
tensor([[ 2.8284,  5.9161, 10.7703,  3.3166],
        [ 5.9161,  2.8284,  5.9161,  7.4833],
        [10.7703,  5.9161,  2.8284, 12.4499],
        [ 3.3166,  7.4833, 12.4499,  2.8284]])
tensor([3.1623, 2.8284, 3.1623])


In [ ]:
def get_mesh_dic():
    mesh_dic = {}
    for i in range(100):
        fnm1 = ''.join([data_dir, test_scan_d, 'test_scan_d_', pairs[i][0], '.ply'])
        fnm2 = ''.join([data_dir, test_scan_d, 'test_scan_d_', pairs[i][1], '.ply'])
        pd1 = PlyData.read(fnm1)
        pd2 = PlyData.read(fnm2)
#         x_coord = pd['vertex'].data['x']
#         y_coord = pd['vertex'].data['y']
#         z_coord = pd['vertex'].data['z']

In [ ]:
# def pd_to_trimesh(pd):
#     vert = np.empty((3, 15000))
#     vert[0] = pd['vertex'].data['x']
#     vert[1] = pd['vertex'].data['y']
#     vert[2] = pd['vertex'].data['z']
#     vert = np.transpose(vert)
    
#     face = pd['face'].data[0]
#     lface = []
#     # array format does not match - moved to list and reconverted to ndarray
#     for i in range(len(face)):
#         lface.append(np.asarray(list(face[i])))
#     nface = np.asarray(lface)
    
#     mesh = trimesh.Trimesh(vertices=vert, faces=nface)
    
#     return mesh

In [1]:


fnm1 = ''.join([data_dir, test_scan_d, 'test_scan_d_', pairs[0][0], '.ply'])
fnm1_1 = ''.join([data_dir, 'training/scan/', 'tr_scan_', pairs[0][0], '.ply'])
fnm2 = ''.join([data_dir, test_scan_d, 'test_scan_d_', pairs[0][1], '.ply'])

asf = trimesh.load(fnm1_1)
asd = trimesh.load(fnm1, file_type='ply', force=None)
# print(asf)
# print(asd)


# 점 x, y, z가 여러개
# print(pd1.elements)
# print(pd2.elements)
# x_coord_1 = pd1['vertex'].data['x']
# y_coord_1 = pd1['vertex'].data['y']
# z_coord_1 = pd1['vertex'].data['z']
# print(len(x_coord_1))
# vertex = np.empty((3, 15000))
# vertex[0, :] = x_coord_1
# vertex[1, :] = y_coord_1
# vertex[2, :] = z_coord_1
# print(len(vertex))
# print(len(vertex[0]))
# vertex = np.transpose(vertex)
# print(vertex)

# option1
# faces_1 = []
# for i in range(len(face_1)):
#     faces_1.append(np.asarray(list(face_1[i])))
# nfaces_1 = np.asarray(faces_1)

# option2
# faces_1 = []
# for i in range(len(face_1)):
#     temp = []
#     temp.append(face_1[i][0])
#     temp.append(face_1[i][1])
#     temp.append(face_1[i][2])
#     nt = np.asarray(temp)
#     faces_1.append(nt)
# nfaces_1 = np.asarray(faces_1)

# mesh1 = trimesh.Trimesh(vertices=vertex, #[pd1['vertex'].data['x'], pd1['vertex'].data['y'], pd1['vertex'].data['z']],
#                         faces=nfaces_1)
# print(mesh1)

# pd1 = PlyData.read(fnm1)
# pd2 = PlyData.read(fnm2)


m1 = trimesh.load(fnm1)
m2 = trimesh.load(fnm2)



# sam1 = trimesh.sample.sample_surface(m1, 5000)
# sam2 = trimesh.sample.sample_surface(m2, 5000)

# # print(sam1[1]) # faces
# # print(m1)
# # print(m1.vertices)
# # print(sam1[0][0])
# if sam1[0][0] in m1.vertices:
#     print("hola")
# for elem in range(len(sam1[0])):
#     same_vert = (m1.vertices==sam1[0][elem])
#     print(same_vert)
#     if same_vert.sum() > 0:
#         sample_shot.append(shot1[same_vert])
# print(len(sample_shot))




# for vert in m1.vertices:
#     if np.all([vert, sam1[0][idx]]) and idx < 5000:
#         shot_index.append(idx)
#         idx += 1
#     if idx == 500:
#         print('checkpt')

# for vertex in sam1.vertices:
#     np.where()


# # get a distance map between two shots
# d_map = compute_l2(shot1, shot2)
# print(d_map)
# torch.save(d_map, 'dist_map.pt')

# calculate_dist_map()

NameError: name 'data_dir' is not defined

In [ ]:
# print(shot1)
# rand_idx = np.random.choice(15000, 5000, replace=False)
# ridx_torch = torch.from_numpy(rand_idx)
# ridx_torch = ridx_torch.to(cuda_device)
# ridx_torch = torch.sort(ridx_torch, dim=-1)[0]
# # print(ridx_torch[0])
# # red_shot = torch.index_select(shot1, dim=0, index=ridx_torch)
# # red_shot2 = torch.index_select(shot2, dim=0, index=ridx_torch)
# # print(red_shot.size())
# # print(red_shot.size())

In [4]:
a = torch.randn(3, 2)
print(a.size()[0])

3


In [20]:
a = torch.tensor([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]])
b = torch.tensor([6, 5])
# b = torch.unsqueeze(b, dim=1)
print(b)
print(b[0] in a[0])
print(a>5)
# c = torch.where(b[0] in a[:], 1, 0)
c = torch.where(torch.eq(a[0], b[0]), 1, 0).sum().item()
print(c)

tensor([6, 5])
False
tensor([[False, False, False, False, False],
        [False, False, False, False,  True]])
0


In [ ]:
#     total_hit = 0 # total_hit = 1000
#     size = dist.size()[0]
#     for i in range(size):
#         # sorts index from smallest to kth smallest
#         if k < size:
#             topk = torch.topk(dist, k, largest=False, sorted=True)

#             knn = np.argpartition(matrix[i], k)[:k]

#             print(knn)
#             smallest = []
#             for j in range(len(knn)):
#                 smallest.append(matrix[i][knn[j]])
#             smallest2 = sorted(matrix[i])[:k]
#             smallest.sort()
#             print("smallest {}".format(smallest))
#             print("smallest2 {}".format(smallest2))
        # same index presents -> hit
#             print("i: {0}, knn: {1}".format(i, knn))

#             if i in knn:
#                 total_hit += 1
#         elif k == size:
#             total_hit += 1
#     return total_hit / size
    
    # information about argpartition
    # https://numpy.org/doc/stable/reference/generated/numpy.argpartition.html
    # https://stackoverflow.com/questions/34226400/find-the-index-of-the-k-smallest-values-of-a-numpy-array
    # if the same index(row = i) presents, then it is hit -> later will be divided by 1000

In [ ]:
    
#     start = torch.cuda.Event(enable_timing=True)
#     end = torch.cuda.Event(enable_timing=True)
    
#     with torch.cuda.device(0):
#         start.record()



#             fnm1 = ''.join([data_dir, test_scan_d, 'test_scan_d_', pairs[i][0], '.ply'])
#             fnm2 = ''.join([data_dir, test_scan_d, 'test_scan_d_', pairs[i][1], '.ply'])
# #             pd1 = PlyData.read(fnm1)
# #             pd2 = PlyData.read(fnm2)
# #             m1 = pd_to_trimesh(pd1)
# #             m2 = pd_to_trimesh(pd2)
#             m1 = trimesh.load(fnm1)
#             m2 = trimesh.load(fnm2)
#             sam1 = trimesh.sample.sample_surface(m1, 5000)
#             sam2 = trimesh.sample.sample_surface(m2, 5000)



#         print(avg_hitrate)
#             d_name = ''.join(['dist_map', pairs[i][0], '_', pairs[i][1], '.pt'])
#             torch.save(d_map, 'dist_map.pt')
#         end.record()
#         print(start.elapsed_time(end))